#! /usr/bin/env python
# -*- coding: utf-8 -*-

import os
import json
import urllib
import socket
import getpass
import ConfigParser
from optparse import OptionParser


def get_server():
    return raw_input("Server: ")


def get_key():
    host = socket.gethostname()
    user = getpass.getuser()
    params = urllib.urlencode({'user': user, 'server': host})
    try:
        f = urllib.urlopen(server + "/register?%s" % params)
        response = json.loads(f.read())
        return response.get('key')
    except:
        print
        print "Invalid Server"
        exit()


def send_message(message):
    params = urllib.urlencode({'key': key, 'message': message})
    try:
        f = urllib.urlopen(server + "/message?%s" % params)
        response = json.loads(f.read())
        if response.get('id'):
            print "Message Saved (" + response.get('message') + ")"
    except:
        print "Error saving the Message"
        exit()


if __name__ == "__main__":

    option_parser = OptionParser()
    opts, args = option_parser.parse_args()

    config_path = os.path.expanduser("~") + '/.messend.conf'

    config = ConfigParser.RawConfigParser()
    config.read(config_path)

    try:
        server = config.get('global', 'server')
        key = config.get('global', 'key')
    except:
        print "Welcome to MesSend"
        print "------------------"
        print "Before anything you need define the server"
        print "Where the messages will be stored"
        print
        config.add_section('global')
        server = get_server()
        config.set('global', 'server', server)
        key = get_key()
        config.set('global', 'key', key)
        with open(config_path, 'wb') as configfile:
            config.write(configfile)
        print
        print "Configuration Success"
        print "You can change the configuration on '~/.messend.conf'"
        print

    if len(args) > 0:
        send_message(args[0])
    else:
        print "The message is required"
        print "Syntax:"
        print "    $ messend \"[message]\""
